### ISSUE TITLE
[ranger] image bug ??!

### ISSUE THREAD

**Issue by duncan-f** [shiva/st#4]
Hello,

I'm a new st terminal user, and i noticed when i browse images in ranger and press a modifier (shift, alt, ctrl, superkey) the image disappear.

Any fix for this ? Or is it a dependency that needs to be installed ?

Thank you.

**Comment by shiva** [comment]
this is just a fork with some of the patches applied. you might want to raise this on the upstream one. I have very little understanding of st

**Comment by duncan-f** [comment]
Ok, thank you.
