### ISSUE TITLE
Adding mousewheel support for zooming in/out?

### ISSUE THREAD

**Issue by ghost** [shiva/st#5]
I'm using Luke Smith's fork of this repo and I couldn't figure out how to submit an issue there, so I decided that it was fine to submit it here instead. I'm hoping that the change that I'm about to suggest will be made in the upstream i.e. this repo, and Luke will notice it so he will merge the changes into his own fork.

I am not informed on the differences between the configurations of your build sources, but in Luke Smith's build he opted to give the Shift+Mousewheel combination the behavior of scrolling up/down the lines of text in the terminal window. While there is a keyboard equivalent to this mouse behavior, the same cannot be said for zooming.

Alluding to the last sentence of the above paragraph; Alt+Shift+J/K is how to increase and decrease the zoom, respectively (I think my memory serves me correctly here). What I wish to propose is to give to the Alt+Shift+Mousewheel combination the functionality of zooming in and out, if that's not too much to ask.

**Comment by xxzozaxx** [comment]
I have done that in my fork, but I use (Alt+Shift) to change language, so I bind it to (Alt+Mousewheel) insteat.
hope you find this helpful,

the change in line 213, 214 in config.h,  all you want to do, to make it Alt+shift, is to change `Mod1Mask` to `Mod1Mask|ShiftMask`, and you know make && sudo make install

EDIT: I forget to mension my [repo](https://github.com/xxzozaxx/st)

**Comment by ghost** [comment]
That saves me some time, thanks for the tip @xxzozaxx . I guess I might as well make the PR to Luke's fork, since this one doesn't seem to be maintained anymore.

Edit: actually while I'm at it, why not just make the PR to both repos.  ¯\_(ツ)_/¯  I can't push it to Luke's though since Github keeps acting weird for some reason.
